mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^', include('tracker.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'))
]

admin.site.site_title = 'Администрирование'
admin.site.index_title = 'Управление сайтом'
admin.site.site_header = 'Администрирование'

tracker/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'tracker'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^railcars/$', views.TrackerView.as_view(), name='railcars'),
    url(r'^railcars/new/$', views.track_create, name='track_new'),
    url(r'^railcars/release/(?P<pk>[0-9]+)/$', views.railcar_release, name='railcar_release'),
    url(r'^railcars/free/(?P<pk>[0-9]+)/$', views.railcar_free, name='railcar_free'),
    url(r'^bills/$', views.BillsListView.as_view(), name='bills'),
    url(r'^bills/new/$', views.bill_create, name='bills_new'),
    url(r'^bills/edit/(?P<pk>[0-9]+)/$', views.BillUpdateView.as_view(), name='bills_edit'),
    url(r'^bills/details/(?P<pk>[0-9]+)/$', views.bill_detail, name='bills_detail'),
    url(r'^tracking/$', views.MonitoringView.as_view(), name='tracking'),
    url(r'^tracking/details/(?P<pk>[0-9]+)/$', views.TrackDetailView.as_view(), name='track_detail'),
    url(r'^login/$', views.MainLoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
]

tracker/models.py
from django.db import models
from django.utils import timezone, formats
from django.contrib.auth.models import User


def month_limit():
    """
    Вычисляет 30 дней от текущей даты, чтобы подставить в payment_date по умолчанию.
    """
    return timezone.localdate() + timezone.timedelta(days=30)


class Bills(models.Model):  # Список платежей
    bill = models.CharField(max_length=32, verbose_name="Номер сделки", unique=True)
    amount = models.DecimalField(max_digits=14, decimal_places=2, verbose_name="Сумма")
    supplier = models.CharField(max_length=32, verbose_name="Поставщик")
    volume = models.IntegerField(default=60, verbose_name="Количество", help_text="Введите количество в тоннах")
    bill_date = models.DateField(default=timezone.localdate, verbose_name="Дата сделки")
    payment_date = models.DateField(null=True, blank=True, verbose_name="Дата оплаты",
                                    help_text="Оставьте поле пустым, если слелка ещё не оплачена")

    class Meta:
        permissions = (
            ("view_bills", "Пользователь может просматривать сделки"),
        )
        verbose_name = 'сделка'
        verbose_name_plural = 'сделки'

    def __str__(self):
        return self.bill


class FuelTypes(models.Model):  # Виды топлива
    id = models.SmallIntegerField(primary_key=True, verbose_name='ИД')
    type = models.CharField(max_length=4, verbose_name="тип")

    class Meta:
        verbose_name = 'тип топлива'
        verbose_name_plural = 'типы топлива'

    def __str__(self):
        return self.type


class Railcars(models.Model):  # Вагоны
    railcar = models.CharField(max_length=8, verbose_name="вагон")
    bill = models.ForeignKey(Bills, null=True, on_delete=models.PROTECT,
                             verbose_name="номер сделки")
    fuel = models.ForeignKey(FuelTypes, on_delete=models.PROTECT, verbose_name="тип топлива")
    volume = models.DecimalField(max_digits=10, decimal_places=4, verbose_name="количество по накладной",
                                 help_text="Введите количество топлива в килограммах")
    is_accepted = models.BooleanField(default=False, verbose_name='принят')
    is_released = models.BooleanField(default=False, verbose_name='отпущен')

    class Meta:
        verbose_name = 'вагон'
        verbose_name_plural = 'вагоны'

    def __str__(self):
        return "{}: {} - {:.0f} кг".format(self.railcar, self.fuel, self.volume)


class Tracking(models.Model):  # Отслеживание вагонов
    time = models.DateTimeField(default=timezone.now, verbose_name="время")
    railcar = models.ForeignKey(Railcars,
                                on_delete=models.PROTECT,
                                verbose_name="Вагон"
                                )
    amount = models.DecimalField(max_digits=10,
                                 decimal_places=4,
                                 verbose_name="Количество факт. ",
                                 help_text="Введите количество топлива в килограммах"
                                 )
    comment = models.TextField(max_length=200,
                               blank=True,
                               default='',
                               verbose_name="Комментарий"
                               )
    accepted_by = models.ForeignKey(User,
                                    null=True,
                                    on_delete=models.PROTECT,
                                    verbose_name="сотрудник"
                                    )
    release_time = models.DateTimeField(null=True, blank=True, verbose_name='отпущен в ')

    class Meta:
        permissions = (
            ("view_tracking", "Пользователь может просматривать принятые вагоны"),
        )
        verbose_name = 'принятый вагон'
        verbose_name_plural = 'принятые вагоны'

    def __str__(self):
        _datetime = self.time.astimezone(timezone.get_current_timezone())
        return '{}: {}'.format(formats.date_format(_datetime, 'SHORT_DATETIME_FORMAT'),
                               self.railcar)

tracker/views.py
from django.urls import reverse_lazy
from django.shortcuts import HttpResponseRedirect, render, get_object_or_404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required, permission_required
from django.utils import timezone

from .forms import RailcarsModelForm, RailcarAddForm, BillsModelForm, TrackingModelForm, MainLoginForm
from .models import Tracking, Bills, Railcars


class TrackerView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    permission_required = 'tracker.add_tracking'
    template_name = 'tracker/tracking.html'
    context_object_name = 'tracking_list'

    def get_queryset(self):
        # Выводим список треков только для текущего пользователя
        queryset = Tracking.objects.filter(accepted_by=self.request.user)
        return queryset.order_by('-time')  # Новые вверху списка


@login_required
@permission_required('tracker.add_tracking')
def railcar_release(request, pk):
    """ Устанавливает статус "отпущен" для вагона и время отпуска для трека """
    if request.method == 'GET':
        track = get_object_or_404(Tracking, pk=pk)
        railcar = track.railcar
        railcar.is_released = True
        railcar.save(update_fields=('is_released',))
        track.release_time = timezone.now()
        track.save(update_fields=('release_time',))
    return HttpResponseRedirect(reverse_lazy('tracker:railcars'))


class TrackDetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    permission_required = 'tracker.view_tracking'
    model = Tracking
    context_object_name = 'track'
    template_name_suffix = '_detail'

    def get_context_data(self, **kwargs):
        context = super(TrackDetailView, self).get_context_data(**kwargs)
        railcar = Railcars.objects.all()
        context['fuel_diff'] = get_fuel_diff(railcar)
        context['date_diff'] = get_date_diff(railcar)
        return context


class BillsListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):  # Вью для вывода списка платежей
    permission_required = 'tracker.view_bills'
    template_name = 'tracker/bills.html'
    # Суммируем количество топлива по вагонам в поле total
    model = Bills
    ordering = ['-bill_date', '-bill']
    context_object_name = 'bills'

    def get_context_data(self, **kwargs):
        context = super(BillsListView, self).get_context_data(**kwargs)
        context['bills_stat'] = get_bill_stat()
        context['railcars_available'] = get_railcars_available()
        context['railcars_for_assign'] = Railcars.objects.filter(bill=None, is_accepted=True).order_by('railcar')
        return context


@login_required
@permission_required('tracker.add_bills')
def bill_detail(request, pk):
    context = {}
    bill = get_object_or_404(Bills, pk=pk)
    railcars = bill.railcars_set.all().order_by('railcar')
    context['bill'] = bill
    context['railcars_list'] = railcars
    context['fuel_diff'] = get_fuel_diff(railcars)
    context['date_diff'] = get_date_diff(railcars)
    context['railcars_available'] = get_railcars_available(bill)
    if request.method == 'POST':
        railcar = get_object_or_404(Railcars, pk=request.POST['railcar'])
        if railcar.bill is None:
            railcar.bill = bill
            railcar.save(update_fields=['bill'])
        return HttpResponseRedirect(reverse_lazy('tracker:bills_detail', kwargs={'pk': pk}))
    else:
        context['railcars_form'] = RailcarAddForm()
    return render(request, template_name='tracker/bills_detail.html', context=context)


@login_required
@permission_required('tracker.add_bills')
def railcar_free(request, pk):
    """ Отвязывает вагон от сделки """
    railcar = get_object_or_404(Railcars, pk=pk)
    bill_pk = railcar.bill_id
    if request.method == 'GET':
        railcar.bill = None
        railcar.save(update_fields=['bill'])
    return HttpResponseRedirect(reverse_lazy('tracker:bills_detail', kwargs={'pk': bill_pk}))


@login_required
@permission_required('tracker.add_bills')
def bill_create(request):
    """ Представление для добавления сделки """
    if request.method == 'POST':
        bill_form = BillsModelForm(request.POST)
        if bill_form.is_valid():
            bill_form.save()
            return HttpResponseRedirect(reverse_lazy('tracker:bills'))
    else:
        bill_form = BillsModelForm()
    return render(request, 'tracker/bills_new.html', {'bill_form': bill_form})


class BillUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    permission_required = 'tracker.add_bills'
    model = Bills
    form_class = BillsModelForm
    context_object_name = 'bill'
    template_name_suffix = '_edit'

    def get_success_url(self):
        return reverse_lazy('tracker:bills_detail', kwargs={'pk': self.object.id})


class MonitoringView(TrackerView):
    permission_required = 'tracker.view_tracking'
    template_name = 'tracker/monitoring.html'

    def get_queryset(self):
        # Выводим список треков для всех пользователей
        queryset = Tracking.objects.all()
        return queryset.order_by('-time')  # Новые вверху списка

    def get_context_data(self, **kwargs):
        context = super(MonitoringView, self).get_context_data(**kwargs)
        context['tracks_stat'] = get_tracks_stat()
        context['railcars_list'] = Railcars.objects.filter(is_accepted=False).order_by('bill__payment_date')
        return context


class MainLoginView(LoginView):
    redirect_authenticated_user = True
    redirect_field_name = 'tracker:index'
    authentication_form = MainLoginForm


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'tracker/index.html'


@login_required
@permission_required('tracker.add_tracking')
def track_create(request):
    """
    Представление для добавления трека.
    Здесь же, в связи с изменением логики, реализовано добавление вагона
    """
    if request.method == 'POST':
        railcar_form = RailcarsModelForm(request.POST)
        if railcar_form.is_valid():
            created_railcar = railcar_form.save(commit=False)
            tracking_form = TrackingModelForm(request.POST)
            if tracking_form.is_valid():
                created_railcar.is_accepted = True
                created_railcar.save()
                tracking_form.instance.railcar = created_railcar
                tracking_form.instance.accepted_by = request.user
                tracking_form.save()
                return HttpResponseRedirect(reverse_lazy('tracker:railcars'))
        else:
            tracking_form = TrackingModelForm(request.POST)
    else:
        railcar_form = RailcarsModelForm()
        tracking_form = TrackingModelForm()
    return render(request, 'tracker/tracking_new.html',
                  {'railcar': railcar_form,
                   'track': tracking_form})


def get_fuel_diff(railcars):
    """
    Получить разницы в количестве топлива
    :return: Словарь разниц между количеством топлива по накладной и фактически принятым
    :rtype: dict
    """
    diff = {}

    for railcar in railcars:
        if Tracking.objects.filter(railcar=railcar).exists():
            track = Tracking.objects.get(railcar=railcar)
            diff[railcar] = railcar.volume - track.amount
    return diff


def get_date_diff(railcars):
    """
    Получить разницы в датах
    :return: Словарь разниц между датой оплаты и временем приёма
    :rtype: dict
    """
    diff = {}

    for railcar in railcars:
        if Tracking.objects.filter(railcar=railcar).exists():
            track = Tracking.objects.get(railcar=railcar)
            if railcar.bill:
                if railcar.bill.payment_date is None:
                    # если оплата ещё не прошла, берём за дату оплаты крайнюю допустимую
                    d = railcar.bill.bill_date + timezone.timedelta(days=5)
                else:
                    d = railcar.bill.payment_date
                # За точку отсчёта принимаем 15:00 даты отгрузки
                dt = timezone.make_aware(timezone.datetime(d.year, d.month, d.day)) + timezone.timedelta(hours=15)
                td = dt - track.time  # type: timezone.timedelta
                diff[railcar] = td
                # else:
                #     diff[railcar] = None  # None если нет привязки к счёту
    return diff


def get_bill_stat():
    """
    Получить статус сделки
    :return: Словарь Сделка : Статус
    :rtype: dict

    Статус:
    0 - успешно принят
    1 - неделя с даты оплаты, есть непринятые вагоны
    2 - различие в количестве топлива
    3 - в процессе приёма (исключено в связи с изменением логики)
    4 - просрочка даты оплаты
    5 - последний день оплаты
    """
    bills_stat = {}
    railcars = Railcars.objects.all()
    fuel_diff = get_fuel_diff(railcars)  # type: dict
    date_diff = get_date_diff(railcars)  # type: dict

    for railcar in date_diff:  # Все вагоны в этом словаре приняты
        bills_stat[railcar.bill] = 0

    for railcar in date_diff:
        if abs(fuel_diff[railcar]) >= 100:  # Погрешность в кг
            bills_stat[railcar.bill] = 2

    today = timezone.now().date()

    bills = Bills.objects.all()
    for bill in bills:
        if bill.payment_date:
            limit = bill.payment_date + timezone.timedelta(days=7)
            if get_railcars_available(bill) > 0 and today >= limit:
                bills_stat[bill] = 1

        else:
            limit = bill.bill_date + timezone.timedelta(days=5)
            if today == limit:
                bills_stat[bill] = 5
            elif today > limit:
                bills_stat[bill] = 4

    return bills_stat


def get_tracks_stat():
    """
    Получить статусы треков
    :return: Словарь Трек : Статус
    :rtype: dict

    Статус:
    0 - успешно принят
    1 - просрочка даты поставки (исключено, проверяется в get_bill_stat)

tracker/templates/tracker/bills.html
{% extends 'tracker/base.html' %}
{% load customfilters %}

{% block title %}
    Сделки
{% endblock %}

{% block header %}
    <div class="header-title">
        Сделки
    </div>
    <nav>
        {% if perms.tracker.view_bills or user.is_superuser %}
            <a role="button" class="btn" href="{% url 'tracker:index' %}">Назад</a>
        {% endif %}
        {% if perms.tracker.add_bills %}
            <a role="button" class="btn" href="{% url 'tracker:bills_new' %}">Добавить сделку</a>
        {% endif %}
        <a role="button" class="btn btn-logout" href="{% url 'tracker:logout' %}">Выход</a>
    </nav>
{% endblock %}

{% block content %}
    {% if railcars_for_assign %}
        <div class="alert alert-info">
            Есть принятые вагоны без информации о сделке:
            {% for railcar in railcars_for_assign %}{% if not forloop.first %}, {% endif %}
                {{ railcar.railcar }}{% endfor %}. Необходимо добавить вагоны в
            соответствующих сделках.
        </div>
    {% endif %}
    {% if bills %}
        <div class="table-responsive">
            <table class="table table-striped table-hover table-bordered">
                <thead>
                <tr>
                    <th>Сделка</th>
                    <th>Вагоны</th>
                    <th>Сумма</th>
                    <th>Поставщик</th>
                    <th>Количество</th>
                    <th>Дата сделки</th>
                    <th>Дата оплаты</th>
                </tr>
                </thead>
                <tbody>
                {% for bill in bills %}
                    {# В зависимости от статуса окрашивается строка #}
                    <tr class="table-row-clickable
                        {% if bills_stat|key:bill == 5 %}danger
                        {% elif bills_stat|key:bill == 4 %}fail
                        {% elif bills_stat|key:bill == 2 %}warning
                        {% elif bills_stat|key:bill == 1 %}info
                        {% elif bills_stat|key:bill == 0 %}success{% endif %}"
                        data-href="{% url 'tracker:bills_detail' bill.id %}">
                        <td>{{ bill.bill }}</td>
                        <td>
                            {% for item in bill.railcars_set.all %}
                                {{ item.railcar }}
                                <br/>
                            {% endfor %}
                        </td>
                        <td>{{ bill.amount.normalize }} р.</td>
                        <td>{{ bill.supplier }}</td>
                        <td>{% if bill.volume %}{{ bill.volume }} т{% endif %}</td>
                        <td>{{ bill.bill_date|date:"d.m.Y" }}</td>
                        <td {% if bills_stat|key:bill == 0 and not bill.payment_date %}style="background-color: #f0b4b4"
                            {% endif %}>
                            {{ bill.payment_date|date:"d.m.Y" }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="table__legend">
            <h5>Статус сделки</h5>
            <span class="track-status alert-success">Все вагоны успешно приняты</span>
            <span class="track-status alert-warning">Расхождение больше 100 кг</span>
            <span class="track-status alert-danger">Последний день оплаты</span>
            <span class="track-status alert-fail">Сделка не оплачена в срок</span>
            <span class="track-status alert-info">Не все вагоны приняты за 7 дней</span>
        </div>
    {% else %}
        Нет данных для отображения.
    {% endif %}
{% endblock %}

{% block scripts %}
    {% load static %}
    <!-- Bootstrap scripts and jQuery support -->
    <script src="{% static 'tracker/js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'tracker/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <!-- Custom scripts -->
    <script src="{% static 'tracker/js/script.js' %}" type="text/javascript"></script>
    <!-->
{% endblock %}

tracker/templates/tracker/bills_detail.html
{% extends 'tracker/base.html' %}
{% load customfilters %}

{% block title %}
    Сделка {{ bill }}
{% endblock %}

{% block header %}
    <span class="header-title">Сделка {{ bill }}</span>
    <nav>
        <a class="btn" href="{% url 'tracker:bills' %}">Назад</a>
        <a class="btn btn-logout" href="{% url 'tracker:logout' %}">Выход</a>
    </nav>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <div class="col-sm-7 col-md-7">
                    <p><b>Номер сделки:</b> {{ bill.bill }}</p>
                    <p><b>Сумма:</b> {{ bill.amount }} р.</p>
                    <p><b>Поставщик:</b> {{ bill.supplier }}</p>
                    <p><b>Количество:</b> {{ bill.volume }} т</p>
                    <p><b>Дата сделки:</b> {{ bill.bill_date|date:"d.m.Y" }}</p>
                    <p><b>Дата оплаты:</b>
                        {% if bill.payment_date %}
                            {{ bill.payment_date|date:"d.m.Y" }}
                        {% else %}
                            <a href="{% url 'tracker:bills_edit' bill.id %}#id_payment_date">Указать</a>
                        {% endif %}
                    </p>
                </div>
                <div class="col-sm-4">
                    <a href="{% url 'tracker:bills_edit' bill.id %}">Редактировать</a>
                </div>
            </div>
        </div>
        <form class="form-block col-sm-6" action="" method="post">
            <div class="form_title">
                <hr/>
                <p><b>Добавить вагон к сделке:</b></p>
            </div>
            {% csrf_token %}
            {% for field in railcars_form %}
                <div class="row form-group">
                    <div class="col-xs-3">
                        {{ field.label_tag }}
                    </div>
                    <div class="col-xs-9">
                        {{ field }}
                        <div class="error field-error">{{ field.errors }}</div>
                        {% if field.help_text %}
                            <span class="helptext">{{ field.help_text|safe }}</span>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            {# Предупреждаем, если вагонов уже достаточно. #}
            {# Аттрибут hidden снимается через jQuery при попытке добавить ещё один. #}
            {% if railcars_available <= 0 %}
                <div id="limit-alert" class="alert alert-warning hidden">
                    <small>Количество вагонов превысит норму для купленного топлива (1 на каждые 60 тонн).
                        Вы уверены, что хотите добавить ещё?
                    </small>
                </div>
            {% endif %}
            <div class="row form-group">
                <div class="col-xs-offset-8 col-xs-4">
                    <input class="btn btn-default" type="submit" value="Добавить"/>
                </div>
            </div>
            <hr/>
        </form>
    </div>
    {% if railcars_list %}
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>Номер вагона</th>
                    <th>Топливо</th>
                    <th>По накладной</th>
                    <th>Факт.</th>
                    <th>Время приема</th>
                    <th>Отпущен</th>
                    <th>Сотрудник</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for railcar in railcars_list %}
                    <tr>
                        <td>{{ railcar.railcar }}</td>
                        <td>{{ railcar.fuel }}</td>
                        <td>{{ railcar.volume.normalize }} кг</td>
                        <td>
                            {% if railcar.is_accepted %}
                                {% for track in railcar.tracking_set.all %}
                                    {{ track.amount.normalize }} кг&nbsp;
                                {% endfor %}
                                {% with fuel_diff|key:railcar as diff %}
                                    {% if diff > 0 %}
                                        <span class="alert-danger">
                                        -{{ diff|floatformat:-4 }} кг
                                    </span>
                                    {% endif %}
                                    {% if diff < 0 %}
                                        <span class="alert-success">
                                        +{{ diff|abs|floatformat:-4 }} кг
                                    </span>
                                    {% endif %}
                                {% endwith %}
                            {% endif %}
                        </td>
                        <td>
                            {% if railcar.is_accepted %}
                                {% for track in railcar.tracking_set.all %}
                                    {{ track.time|date:"j.m.Y H:i:s" }} &nbsp;
                                {% endfor %}
                            {% endif %}
                        </td>
                        <td>
                            {% if not railcar.is_released %}
                                <span class="alert-danger">на базе</span>
                            {% else %}
                                {% for track in railcar.tracking_set.all %}
                                    {{ track.release_time|date:"H:i" }}
                                {% endfor %}
                            {% endif %}
                        </td>
                        <td>
                            {% if railcar.is_accepted %}
                                {% for track in railcar.tracking_set.all %}
                                    {% firstof track.accepted_by.get_full_name track.accepted_by.get_short_name track.accepted_by.get_username %}
                                {% endfor %}
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'tracker:railcar_free' railcar.id %}">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{% endblock %}
{% block scripts %}
    {% load static %}
    <!-- Bootstrap scripts and jQuery support -->
    <script src="{% static 'tracker/js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        {# Выводим уведомление о превышении количества вагонов при привязке еще одного. #}
        $(document).ready(function () {
            $('#id_railcar').change(function () {
                $('#limit-alert').toggleClass('hidden');
            });
        });
    </script>
    <!-->
{% endblock %}

tracker/templates/tracker/bills_edit.html
{% extends 'tracker/base.html' %}
{% block title %}
    Редактирование сделки
{% endblock %}
{% block header %}
    <span class="header-title">Редактирование сделки</span>
    <nav>
        <a class="btn" href="{% url 'tracker:bills_detail' bill.id %}">Назад</a>
        <a class="btn btn-logout" href="{% url 'tracker:logout' %}">Выйти</a>
    </nav>
{% endblock %}
{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="row form-group">
                <div class="col-sm-offset-1 col-sm-3 col-md-offset-2 col-md-2">
                    {{ field.label_tag }}
                </div>
                <div class="col-sm-7 col-md-6">
                    {{ field }}
                    <div class="error field-error">{{ field.errors }}</div>
                    {% if field.help_text %}
                        <span class="helptext">{{ field.help_text|safe }}</span>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <div class="row form-group">
            <div class="col-xs-offset-8 col-sm-offset-9 col-sm-2 col-md-offset-8">
                <input class="btn btn-default" type="submit" value="Сохранить"/>
            </div>
        </div>
    </form>
{% endblock %}

tracker/templates/tracker/index.html
{% extends 'tracker/base.html' %}

{% block title %}
    Главная
{% endblock %}

{% block header %}
    <span class="header-title">Главная</span>
    <span class="user-welcome">Добро пожаловать, {% firstof user.get_short_name user.get_username %}</span>
    <nav>
        <a role="button" class="btn btn-logout" href="{% url 'tracker:logout' %}">Выход</a>
    </nav>
{% endblock %}

{% block content %}
    <div class="index-menu">
        {% if perms.tracker.view_tracking and perms.tracker.view_bills %}
            <a role="button" class="btn btn-default index-menu__entry"
               href="{% url 'tracker:tracking' %}">Трекинг</a>
        {% endif %}
        {% if perms.tracker.add_tracking %}
            <a role="button" class="btn btn-default index-menu__entry"
               href="{% url 'tracker:railcars' %}">Прием вагонов</a>
        {% endif %}
        {% if perms.tracker.view_bills %}
            <a role="button" class="btn btn-default index-menu__entry"
               href="{% url 'tracker:bills' %}">Сделки</a>
        {% endif %}
        {% if user.is_superuser %}
            <a role="button" class="btn btn-default index-menu__entry"
               href="/admin/">Администрирование</a>
        {% endif %}
    </div>
{% endblock %}

tracker/templates/tracker/tracking.html
{% extends 'tracker/base.html' %}

{% block title %}
    Принятые вагоны
{% endblock %}

{% block header %}
    <span class="header-title">Список принятых вагонов</span>
    <nav>
        {% if not perms.tracker.add_tracking or user.is_superuser %}
            <a role="button" class="btn" href="{% url 'tracker:index' %}">Назад</a>
        {% endif %}
        {% if perms.tracker.add_tracking %}
            <a role="button" class="btn" href="{% url 'tracker:track_new' %}">Принять вагон</a>
        {% endif %}
        <a role="button" class="btn btn-logout" href="{% url 'tracker:logout' %}">Выход</a>
    </nav>
{% endblock %}

{% block content %}
    {% if tracking_list %}
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>№</th>
                    <th>Время</th>
                    <th>Номер вагона</th>
                    <th>Топливо</th>
                    <th>Количество</th>
                    <th>Комментарий</th>
                    <th>Отпущен</th>
                </tr>
                </thead>
                <tbody>
                {% for track in tracking_list %}
                    <tr>
                        <td>{{ track.id }}</td>
                        <td>{{ track.time|date:"d.m.y H:i:s" }}</td>
                        <td>{{ track.railcar.railcar }}</td>
                        <td>{{ track.railcar.fuel }}</td>
                        <td>{{ track.amount.normalize }} кг</td>
                        <td>{{ track.comment }}</td>
                        <td>
                            {% if not track.railcar.is_released %}
                                <a class="btn btn__release"
                                   href="{% url 'tracker:railcar_release' track.id %}">Отпустить</a>
                            {% else %}
                                {{ track.release_time|date:"H:i" }}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        Нет принятых вами вагонов. Вы можете <a href="{% url 'tracker:track_new' %}">принять</a> вагон.
    {% endif %}
{% endblock %}